const items = [{
    id: '001',
    image: '/photos/img5.jpg',
    package_info: '26+ Packages',
    destination_info: 'Himachal Pradesh',
    price: '₹ 8,800',
},
{
    id: '002',
    image: '/photos/img6.jpg',
    package_info: '18+ Packages',
    destination_info: 'Kerala',
    price: '₹ 18,000',
},{
    id: '003',
    image: '/photos/img7.jpg',
    package_info: '4+ Packages',
    destination_info: 'Jammu & Kashmir',
    price: '₹ 20,500',
},{
    id: '004',
    image: '/photos/img8.jpg',
    package_info: '10+ Packages',
    destination_info: 'Meghalya',
    price: '₹ 21,000',
},{
    id: '005',
    image: '/photos/img9.jpg',
    package_info: '22+ Packages',
    destination_info: 'Uttarakhand',
    price: '₹ 10,500',
},{
    id: '006',
    image: '/photos/img10.jpg',
    package_info: '38+ Packages',
    destination_info: 'Karnatka',
    price: '₹ 17,000',
},{
    id: '007',
    image: '/photos/img11.jpg',
    package_info: '27+ Packages',
    destination_info: 'Rajasthan',
    price: '₹ 15,000',
},{
    id: '008',
    image: '/photos/img12.jpg',
    package_info: '6+ Packages',
    destination_info: 'Andaman & Nicobar',
    price: '₹ 15,600',
},{
    id: '009',
    image: '/photos/img13.jpg',
    package_info: '11+ Packages',
    destination_info: 'Goa',
    price: '₹ 12,000',
},{
    id: '010',
    image: '/photos/img14.jpg',
    package_info: '14+ Packages',
    destination_info: 'Sikkim',
    price: '₹ 13,500',
},{
    id: '011',
    image: '/photos/img15.jpg',
    package_info: '2+ Packages',
    destination_info: 'Arunachal Pradesh',
    price: '₹ 17,500',
},{
    id: '012',
    image: '/photos/img17.jpg',
    package_info: '1+ Packages',
    destination_info: 'Assam',
    price: '₹ 19,000',
},{
    id: '013',
    image: '/photos/img16.jpg',
    package_info: '3+ Packages',
    destination_info: 'Gujarat',
    price: '₹ 18,500',
},{
    id: '014',
    image: '/photos/img18.jpg',
    package_info: '13+ Packages',
    destination_info: 'Ladakh',
    price: '₹ 16,000',
},{
    id: '015',
    image: '/photos/img19.jpg',
    package_info: '22+ Packages',
    destination_info: 'Madhya Pradesh',
    price: '₹ 15,000',
},{
    id: '016',
    image: '/photos/img20.jpg',
    package_info: '1+ Packages',
    destination_info: 'Nagaland',
    price: '₹ 22,000',
},]